# Generated by Django 4.1.3 on 2022-12-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='end',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joining_year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passout_year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='start',
            field=models.IntegerField(default=None),
        ),
    ]
