# Generated by Django 4.1.4 on 2022-12-29 18:03

import accounts.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile/default.jpg', upload_to=accounts.views.upload_to, verbose_name='Image'),
        ),
    ]
