# Generated by Django 4.1.3 on 2022-12-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
