# Generated by Django 4.1.3 on 2023-01-02 12:13

import accounts.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_picture',
            field=models.ImageField(default='profile/recruiter/default.jpg', upload_to=accounts.views.upload_to, verbose_name='Image'),
        ),
    ]
