# Generated by Django 4.1.4 on 2023-01-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='post_balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
