# Generated by Django 4.1.4 on 2023-01-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_recruiterprofile_post_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_mobile',
            field=models.CharField(max_length=10),
        ),
    ]
