# Generated by Django 4.1.4 on 2023-01-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_recruiterprofile_company_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_email',
            field=models.EmailField(max_length=30),
        ),
    ]
