# Generated by Django 4.1.3 on 2023-01-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
