# Generated by Django 4.1.3 on 2023-01-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_recruiterprofile_profile_picture'),
        ('recruiter', '0002_delete_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('vacancies', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=30)),
                ('type', models.CharField(default='Full Time', max_length=30)),
                ('workmode', models.CharField(default='On-Site', max_length=30)),
                ('experience_from', models.IntegerField()),
                ('experience_to', models.IntegerField()),
                ('job_description', models.TextField()),
                ('criteria', models.TextField()),
                ('payscale_from', models.IntegerField(blank=True, null=True)),
                ('payscale_to', models.IntegerField(blank=True, null=True)),
                ('applicants', models.IntegerField(default=0)),
                ('hired', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recruiterprofile')),
            ],
        ),
    ]
