# Generated by Django 4.1.3 on 2023-01-03 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_recruiterprofile_profile_picture'),
        ('recruiter', '0004_alter_job_category_alter_job_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.recruiterprofile'),
        ),
    ]
