# Generated by Django 4.1.3 on 2023-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_alter_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_from',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_to',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='payscale_from',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='payscale_to',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancies',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
