# Generated by Django 4.1.4 on 2023-01-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_alter_job_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
