# Generated by Django 4.1.4 on 2023-01-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_recruiterprofile_post_balance'),
        ('recruiter', '0010_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.recruiterprofile'),
        ),
    ]
