# Generated by Django 4.1.4 on 2023-01-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_recruiterprofile_post_balance'),
        ('recruiter', '0011_jobapplication_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recruiterprofile'),
        ),
    ]
