# Generated by Django 4.1.4 on 2023-01-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_razorpaypayment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaypayment',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
    ]
