# Generated by Django 4.1.4 on 2023-01-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPlan',
            new_name='PostPlans',
        ),
    ]
